// Autogenerated from Pigeon (v2.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, StandUpResult) {
  StandUpResultBad = 0,
  StandUpResultGood = 1,
  StandUpResultBetter = 2,
  StandUpResultAmazing = 3,
};

typedef NS_ENUM(NSUInteger, FitnessRequestPermissionResult) {
  FitnessRequestPermissionResultGranted = 0,
  FitnessRequestPermissionResultFitnessNotGranted = 1,
  FitnessRequestPermissionResultFitnessNotInstalled = 2,
  FitnessRequestPermissionResultNoGoogleAccountConfirmed = 3,
};

@class NativeStepList;
@class NativeStep;
@class StandUpHourResult;
@class StandUpResultInDate;
@class StandUpRequestDuration;
@class StandUpResults;
@class FitnessRequestPermissionResultObject;

@interface NativeStepList : NSObject
+ (instancetype)makeWithRecords:(nullable NSArray<NativeStep *> *)records;
@property(nonatomic, strong, nullable) NSArray<NativeStep *> * records;
@end

@interface NativeStep : NSObject
+ (instancetype)makeWithDate:(nullable NSString *)date
    distance:(nullable NSNumber *)distance
    steps:(nullable NSNumber *)steps;
@property(nonatomic, copy, nullable) NSString * date;
@property(nonatomic, strong, nullable) NSNumber * distance;
@property(nonatomic, strong, nullable) NSNumber * steps;
@end

@interface StandUpHourResult : NSObject
+ (instancetype)makeWithHour:(nullable NSNumber *)hour
    result:(StandUpResult)result;
@property(nonatomic, strong, nullable) NSNumber * hour;
@property(nonatomic, assign) StandUpResult result;
@end

@interface StandUpResultInDate : NSObject
+ (instancetype)makeWithValue:(nullable NSArray<StandUpHourResult *> *)value
    errorMessage:(nullable NSString *)errorMessage;
@property(nonatomic, strong, nullable) NSArray<StandUpHourResult *> * value;
@property(nonatomic, copy, nullable) NSString * errorMessage;
@end

@interface StandUpRequestDuration : NSObject
+ (instancetype)makeWithDateFormat:(nullable NSString *)dateFormat
    startDate:(nullable NSString *)startDate
    endDate:(nullable NSString *)endDate;
@property(nonatomic, copy, nullable) NSString * dateFormat;
@property(nonatomic, copy, nullable) NSString * startDate;
@property(nonatomic, copy, nullable) NSString * endDate;
@end

@interface StandUpResults : NSObject
+ (instancetype)makeWithDuration:(nullable StandUpRequestDuration *)duration
    results:(nullable NSDictionary<NSString *, NSArray<id> *> *)results;
@property(nonatomic, strong, nullable) StandUpRequestDuration * duration;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSArray<id> *> * results;
@end

@interface FitnessRequestPermissionResultObject : NSObject
+ (instancetype)makeWithValue:(FitnessRequestPermissionResult)value;
@property(nonatomic, assign) FitnessRequestPermissionResult value;
@end

/// The codec used by FlutterCallNativeApi.
NSObject<FlutterMessageCodec> *FlutterCallNativeApiGetCodec(void);

@protocol FlutterCallNativeApi
- (void)getTodayStepWithCompletion:(void(^)(NativeStep *_Nullable, FlutterError *_Nullable))completion;
- (void)getHistoryStepsWithCompletion:(void(^)(NativeStepList *_Nullable, FlutterError *_Nullable))completion;
- (void)getLast2DaysStepsWithCompletion:(void(^)(NativeStepList *_Nullable, FlutterError *_Nullable))completion;
- (void)getStepsStartDate:(NSString *)startDate endDate:(NSString *)endDate completion:(void(^)(NativeStepList *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FlutterCallNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterCallNativeApi> *_Nullable api);

/// The codec used by FlutterCallIosNativeApi.
NSObject<FlutterMessageCodec> *FlutterCallIosNativeApiGetCodec(void);

@protocol FlutterCallIosNativeApi
- (void)healthAuthorizationRequestMethodWithCompletion:(void(^)(FlutterError *_Nullable))completion;
- (void)isHealthKitDeniedWithCompletion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)monitorBackgroundStepChangedWithCompletion:(void(^)(NativeStep *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FlutterCallIosNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterCallIosNativeApi> *_Nullable api);

/// The codec used by NativeCallFlutterApi.
NSObject<FlutterMessageCodec> *NativeCallFlutterApiGetCodec(void);

@interface NativeCallFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)uploadBackgroundLast2DaysStepsList:(NativeStepList *)list completion:(void(^)(NSError *_Nullable))completion;
- (void)showLocalNotificationWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by StandUpApi.
NSObject<FlutterMessageCodec> *StandUpApiGetCodec(void);

@protocol StandUpApi
- (void)getStandUpAtDate:(NSString *)date dateFormat:(NSString *)dateFormat completion:(void(^)(StandUpResultInDate *_Nullable, FlutterError *_Nullable))completion;
- (void)getStandUpDuration:(StandUpRequestDuration *)duration completion:(void(^)(StandUpResults *_Nullable, FlutterError *_Nullable))completion;
@end

extern void StandUpApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StandUpApi> *_Nullable api);

/// The codec used by AndroidFitnessApi.
NSObject<FlutterMessageCodec> *AndroidFitnessApiGetCodec(void);

@protocol AndroidFitnessApi
- (void)googleSignInHasPermissionsWithCompletion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)requestFitnessPermissionStatusWithCompletion:(void(^)(FitnessRequestPermissionResultObject *_Nullable, FlutterError *_Nullable))completion;
@end

extern void AndroidFitnessApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AndroidFitnessApi> *_Nullable api);

NS_ASSUME_NONNULL_END
