package jp.co.felicapocketmk.karadalive_flutter_plugin.define

enum class DateFormatType(var formatString: String) {
    HMS24("HH:mm:ss"),
    HM24("HH:mm"),
    H24("HH"),
    M("mm"),
    Y("yyyy"),
    D("d"),
    YM("yyyyMM"),
    YM_DOT("yyyy.MM"),
    YMD("yyyyMMdd"),
    YMDHMS_24("yyyyMMddHHmmss"),
    YM_JAPANESE("yyyy年 M月"),
    YMD_JAPANESE("yyyy年M月d日"),
    MD_JAPANESE("M月d日"),
    MD_DAY_OF_THE_WEEK_JAPANESE("M月d日(E)"),
    YM_HYPHEN("yyyy-MM"),
    YMD_DOT("yyyy.MM.dd"),
    YMD_HYPHEN("yyyy-MM-dd"),
    YMD_HMS_HYPHEN("yyyy-MM-dd hh:mm:ss"),
    YMD_HMS_HYPHEN_24("yyyy-MM-dd HH:mm:ss"),
    YMD_SLASH("yyyy/MM/dd"),
    YMD_HMS_SLASH("yyyy/MM/dd hh:mm:ss"),
    YMD_HMS_SLASH_24("yyyy/MM/dd HH:mm:ss"),
    YMD_DAY_OF_THE_WEEK_SLASH("yyyy/MM/dd(E)"),
    YMD_DAY_OF_THE_WEEK("yyyy年M月d日(E)"),
    YMD_HM_DAY_OF_THE_WEEK("yyyy年M月d日(E) hh:mm"),
    YMD_HM_DAY_OF_THE_WEEK_24("yyyy年M月d日(E) HH:mm"),
    DAY("d日"),
    DAY_OF_THE_WEEK("E"),
    MONTH_OF_YEAR("M月(yyyy)"),
    MD_DAY_OF_THE_WEEK_SLASH("MM/dd(E)"),
}
